### ISSUE TITLE
Hang up for a long time and enter failed in about half an hour

### ISSUE THREAD

**Issue by tinnkai** [hibiken/asynqmon#212]
How to solve this situation? Thank you.
![1643990450(1)](https://user-images.githubusercontent.com/2200272/152561183-c28cac0d-c984-47fa-925b-d377c30a0d05.jpg)

**Comment by hibiken** [comment]
@tinnkai thank you for opening an issue!

Would you mind showing the output of 

```sh
redis-cli ZRANGE asynq:{default}:deadlines 0 -1 WITHSCORES
```

**Comment by tinnkai** [comment]
@hibiken 
![image](https://user-images.githubusercontent.com/2200272/152634928-e5f39a14-10f8-44c9-999c-b3ee9734ce00.png)
It may be caused by the direct shutdown of the service while the queue is being processed,But what I expect can I keep the failure queue and then I can do it manually.
thank you

**Comment by tinnkai** [comment]
@hibiken 
Sorry, I misunderstood. Processed includes the number of failed and successful, that is, entering failed will retry
![image](https://user-images.githubusercontent.com/2200272/152642676-5c418ba6-9766-43cb-a58b-6d0b5698ee28.png)

**Comment by hibiken** [comment]
@tinnkai Thanks for providing additional info!

I think initial confusion around task being stuck in "active" state is due to how the task recovery works currently when a worker crashes (or forced killed `kill -9`). Currently, asynq recovers task if its deadline has expired over 30s ago, but we have an open issue to improve this by recovering these orphaned tasks more quickly (https://github.com/hibiken/asynq/issues/334).
