### ISSUE TITLE
Could not retrieve queues live data — See the logs for details

### ISSUE THREAD

**Issue by charliecen** [hibiken/asynqmon#335]
get api/queues
response 500 error
```sh
UNKNOWN: UNKNOWN: redis eval error: ERR Error running script (call to f_0c80fc1868e3aae205155ae2017ce995a3a7cec0): @user_script:30: user_script:30: attempt to perform arithmetic on local 'bytes' (a boolean value)
```

redis: v6.2.5
asynq: v0.24.1
asynqmon: v0.7.2

**Comment by charliecen** [comment]
docker labels
```sh
"org.opencontainers.image.created": "2023-07-04T03:13:04.321Z",
"org.opencontainers.image.description": "Web UI for Asynq task queue",
"org.opencontainers.image.licenses": "MIT",
"org.opencontainers.image.revision": "d1b889456de3c98c22de24642b6f836a29da3140",
"org.opencontainers.image.source": "https://github.com/hibiken/asynqmon",
"org.opencontainers.image.title": "asynqmon",
"org.opencontainers.image.url": "https://github.com/hibiken/asynqmon",
"org.opencontainers.image.version": "0.7.2"
```

go.mod
```
github.com/hibiken/asynq v0.24.1
```

go: v1.18

**Comment by wwqwq2313** [comment]
Hello, we tried to solve the issue.

This is what we did:

Update newListQueuesHandlerFunc to handle potential Redis Lua script errors gracefully. This addresses the issue where the API returns a 500 error due to an arithmetic operation on a boolean value in the Redis script.

You can review changes in this commit: https://github.com/wwqwq2313/hibiken-asynqmon-335/commit/5dc75c13cce518865a001e94c2b85c3e73a315d8.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

Latta AI seeks to solve problems in open source projects as part of its mission to support developers around the world. Learn more about our mission at https://latta.ai/ourmission . If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by charliecen** [comment]
@wwqwq2313  
Thank you for your reply
I'll try to see if it's possible

**Comment by charliecen** [comment]
@hibiken

**Comment by charliecen** [comment]
![WX20241225-180116@2x](https://github.com/user-attachments/assets/03052369-f74d-449f-beb2-00eba390a834)

**Comment by charliecen** [comment]
```golang
func newListQueuesHandlerFunc(inspector *asynq.Inspector) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		qnames, err := inspector.Queues()
		if err != nil {
			http.Error(w, fmt.Sprintf("Error fetching queues: %v", err), http.StatusInternalServerError)
			return
		}
		snapshots := make([]*queueStateSnapshot, len(qnames))
		for i, qname := range qnames {
			qinfo, err := inspector.GetQueueInfo(qname)
			if err != nil {
				if strings.Contains(err.Error(), "attempt to perform arithmetic on local 'bytes' (a boolean value)") {
					// Handle the specific Redis Lua script error
					snapshots[i] = &queueStateSnapshot{Queue: qname}
					continue
				}
				http.Error(w, fmt.Sprintf("Error fetching queue info for %s: %v", qname, err), http.StatusInternalServerError)
				return
			}
			snapshots[i] = toQueueStateSnapshot(qinfo)
		}
		payload := map[string]interface{}{"queues": snapshots}
		json.NewEncoder(w).Encode(payload)
	}
}
```
Problem has been solved!!!
